### ISSUE TITLE
혹시 공부 목적으로 참고해도 될까요!?

### ISSUE THREAD

**Issue by JP-5010** [herjh0405/DACON_Meal#1]
.

**Comment by herjh0405** [comment]
죄송합니다 ㅠㅠ 저건 현재 진행중인 대회라서요. 
다른 것들은 편하게 참고하셔도 괜찮습니다 ㅎㅎ
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-06-13 (일) 16:22:34 (GMT+09:00)
Subject: [herjh0405/DACON_Meal] 혹시 공부 목적으로 참고해도 될까요!? (#1)
 
.
